# Generated by Django 5.2.8 on 2025-11-29 03:18

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_rut_alter_inventory_reorder_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rut',
            field=models.CharField(max_length=12, validators=[api.models.validate_rut]),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
