# Generated by Django 5.2.8 on 2025-11-29 06:49

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_branch_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_provider',
            field=models.BooleanField(default=False, help_text='Marca si esta es la empresa proveedora (TemucoSoft)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(help_text='Teléfono (ej: +56912345678)', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?56\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='rut',
            field=models.CharField(help_text='RUT de la empresa (ej: 76.123.456-7)', max_length=12, unique=True, validators=[api.models.validate_rut]),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?56\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?56\\d{9}$')]),
        ),
    ]
